AWSTemplateFormatVersion: 2010-09-09
Description: Create a role for us to assume and create resource will have acess to
Parameters:
  BucketName:
    Type: String
    Default: mybucket-sts-0012
Resources:
  StsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: s3acess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource:
                  - !Sub arn:aws:s3:::${BucketName}
                  - !Sub arn:aws:s3:::${BucketName}/*