#!/usr/bin/env bash 


# check for bucket name (argument )

if [ -z "$1" ]; then
  echo "provide bucket name - "
  exit 1
fi
REGION="ca-central-1"
BUCKET_NAME=$1
aws s3api create-bucket \
 --bucket $BUCKET_NAME \
 --create-bucket-configuration="LocationConstraint=$REGION" #only if region outside 'us-east-1'

