#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "There needs to be a bucket name eg. ./delete-objects my-bucket-name"
  exit 1
fi

BUCKET_NAME=$1

echo "Listing objects in bucket: $BUCKET_NAME"

aws s3api list-objects-v2 \
  --bucket "$BUCKET_NAME" \
  --query 'Contents[].Key' \
| jq -n '{Objects: [inputs | .[] | {Key: .}]} ' \
> /tmp/delete_objects.json

echo "Deleting objects..."

aws s3api delete-objects \
  --bucket "$BUCKET_NAME" \
  --delete file:///tmp/delete_objects.json

echo "Done."