#!/usr/bin/env bash 

echo "sorted bucket according to creation"


aws s3api list-buckets \
| jq -r '
  .Buckets
  | sort_by(.CreationDate)
  | reverse
  | if length > 5
    then (.[0:5] | .[].Name), "..."
    else .[].Name
    end
'





#./s3/bash_script/list-object