#!/usr/bin/env bash

echo "putting object in bucket - $1"

# check bucket
if [ -z "$1" ]; then
  echo "provide bucket name"
  exit 1
fi

# check file
if [ -z "$2" ]; then
  echo "provide file path"
  exit 1
fi

# check content-type
if [ -z "$3" ]; then
  echo "provide content-type"
  exit 1
fi

BUCKET_NAME=$1
FILE_NAME=$2
CONTENT_TYPE=$3

# object key = file name only
OBJECT_KEY=$(basename "$FILE_NAME")

# verify file exists
if [ ! -f "$FILE_NAME" ]; then
  echo "error: file not found -> $FILE_NAME"
  exit 1
fi

echo "> aws s3api put-object --bucket $BUCKET_NAME --key $OBJECT_KEY --content-type $CONTENT_TYPE --body $FILE_NAME"

aws s3api put-object \
  --bucket "$BUCKET_NAME" \
  --key "$OBJECT_KEY" \
  --content-type "$CONTENT_TYPE" \
  --body "$FILE_NAME"


#./s3/bash_script/put-object <bucket-name> <file-path> <content-type>

#./s3/bash_script/put-object prescription-images-dev-main hello.txt plain/txt
