#!/usr/bin/env bash 

# where we will store these files 
OUTPUT_DIR="./tmp/files"

rm -r $OUTPUT_DIR

mkdir -p $OUTPUT_DIR

for((i=1; i<=10; i++));
do 
  touch "$OUTPUT_DIR/file_$i.txt"
  echo "file_$i.txt" > "$OUTPUT_DIR/file_$i.txt"
done







