#!/usr/bin/env bash 

echo "syncing files to bucket -"

OUTPUT_DIR="./tmp/files"

# check bucket name
if [ -z "$1" ]; then
  echo "provide bucket name"
  exit 1
fi

REGION="us-east-1"
BUCKET_NAME=$1


# recreate directory safely
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# generate files
for ((i=1; i<=10; i++))
do 
  FILE="$OUTPUT_DIR/file_$i.txt"
  echo "file_$i.txt" > "$FILE"
done

# sync to S3
aws s3 sync "$OUTPUT_DIR" "s3://$BUCKET_NAME"