#!/usr/bin/env bash 
set -e

#create our vpc
VPC_ID=$(
aws ec2 create-vpc \
  --cidr-block "172.1.0.0/16" \
  --region us-east-1 \
  --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=MyVpc-3}]' \
  --query 'Vpc.{VpcId:VpcId}' \
  --output text
)

echo $VPC_ID

# configure vpc to have dns hostname turned on
aws ec2 modify-vpc-attribute \
--vpc-id $VPC_ID \
--enable-dns-hostnames

#create an IGW 
IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text
)

echo $IGW_ID

#attach an IGW
aws ec2 attach-internet-gateway \
--internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID

# create a new subnet
SUBNET_ID=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block 172.1.0.0/20 \
--query Subnet.SubnetId \
--output text
)

echo $SUBNET_ID

# configure subnet to have auto assign public ipv4
aws ec2 modify-subnet-attribute \
--subnet-id $SUBNET_ID \
--map-public-ip-on-launch

# explicty associate subnet 

#get default route table id
ROUTE_TABLE_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" \
--query 'RouteTables[0].RouteTableId' \
--output text
)

echo $ROUTE_TABLE_ID

#get association id
ASSOCIATION_ID=$(aws ec2 associate-route-table \
--route-table-id $ROUTE_TABLE_ID \
--subnet-id $SUBNET_ID \
--query 'AssociationId' \
--output text
)

echo $ASSOCIATION_ID

# add a route to our RT to our IGW
aws ec2 create-route \
--route-table-id $ROUTE_TABLE_ID \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id $IGW_ID

echo "./delete_vpc $VPC_ID $SUBNET_ID $IGW_ID $ROUTE_TABLE_ID $ASSOCIATION_ID"